name: "Setup"
description: "setup environment"
runs:
  using: "composite"
  steps:
    - name: Set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3
    - name: Install asdf & tools
      uses: asdf-vm/actions/setup@v2
    - name: Setup
      shell: bash
      run: make bootstrap
